stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/
