stages:
  - build

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace --debug
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/
