stages:
  - build

before_script:
  - chmod +x ./gradlew
  - export GRADLE_OPTS="-Dorg.gradle.daemon=false"

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/
