stages:
  - build

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew assembleDebug -Dkotlin.compiler.execution.strategy="in-process"
  tags:
    - android
  artifacts:
    paths:
      - app/build/outputs/
