image: docker-android-sdk:alpine-standalone

stages:
  - build

before_script:
  - chmod +x ./gradlew

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  tags:
    - linux
    - docker
  artifacts:
    paths:
      - app/build/outputs/
